# based on https://poetryincode.dev/testing-dart-packages-with-github-actions
name: Test And Publish

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test_pub:
    runs-on: ubuntu-latest # was macos-latest to maximize misc plugin support

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: '2.0.4'

      - name: Pull dependencies
        run: flutter pub get

      - name: Test app
        run: flutter test --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage/lcov.info

      # Generate flutter web app
      - uses: erickzanardo/flutter-gh-pages@v3
        with:
          workingDir: build/ghpages
          webRenderer: canvaskit
